import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Wazarabi Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <section className="bg-blue-700 min-h-screen">
          <p className="text-3xl font-bold underline">HELLO THERE MF, HAHAH TAILWIND WORKS !!!</p>
        </section>
      </main>
    </>
  )
}
